### ISSUE TITLE
NullPointerException in Login

### ISSUE THREAD

**Issue by alrawi** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#20]
Hello,
I am trying to get Kam1n0 installed on a Windows 10 64 bit machine with IDA 6.8. The plugin seems to install fine along with the server component. The issue I ran into is trying to login or create an account. In the Web UI I click on the Login link in the upper right, but I am not able to proceed. I checked the JS logs in the HTML page and it seems that there is NullPointerException in the server component.

Here is the message from the JS console:
```
{timestamp: 1528022469514, status: 500, error: "Internal Server Error",…}
error:"Internal Server Error"
exception:"java.lang.NullPointerException"
message:"No message available"
path:"/login"
status:500
timestamp:1528022469514
```

Here is the Java message from the Kam1n0 server console:
```
java.lang.NullPointerException: null
	at ca.mcgill.sis.dmas.kam1n0.AppPlatform$PrioritizeInterceptor.preHandle(AppPlatform.java:188) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:133) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:962) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[kam1n0-server.jar:2.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[kam1n0-server.jar:2.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[kam1n0-server.jar:2.0.0]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[kam1n0-server.jar:2.0.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [kam1n0-server.jar:2.0.0]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [kam1n0-server.jar:2.0.0]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [kam1n0-server.jar:2.0.0]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [kam1n0-server.jar:2.0.0]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [kam1n0-server.jar:2.0.0]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [kam1n0-server.jar:2.0.0]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [kam1n0-server.jar:2.0.0]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [kam1n0-server.jar:2.0.0]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [kam1n0-server.jar:2.0.0]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [kam1n0-server.jar:2.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [kam1n0-server.jar:2.0.0]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]
```

**Comment by alrawi** [comment]
I figured it out, it was a path issue. I needed to set the right data path for the program to run.

**Comment by LiamKarlMitchell** [comment]
How can we set the right data path?

Edit never mind.
Had to set it in properties, work bench and program wouldn't run as I needed to make it use right version of java even though I had installed 8.

Edited this into the top of the bat script.
```
set JAVA_HOME="C:\Program Files\Java\jre1.8.0_172"
set PATH=%JAVA_HOME%\bin;%PATH%
```

And modified a copy of the bat to run the work bench as well.

**Comment by Edemos1er** [comment]
@alrawi I am facing the same problem as you some years ago. Please help me. How to set the right data path? Thank you

@LiamKarlMitchell please I need your help.

**Comment by Vulmatch** [comment]
@Edemos1er  I encountered the very similar issue: java.lang.NullPointerException: null. After a detail inspect I found that the problem occurs at the last line in Kam1n0 panel: at java.lang.Thread.run(Unknown Source) [na:1.8.0_301] (because I installed jre 8u301). I reinstalled to jre 8u172 and it solved my problem. And btw, you need to run with admin privilege otherwise have error.

jre 8u172 download link:

https://www.oracle.com/au/java/technologies/javase/javase8-archive-downloads.html

**Comment by Edemos1er** [comment]
Thanks a lot for your reply. I really appreciate it.

+228 98258054
+228 90530940

Le dim. 17 oct. 2021 à 23:39, LeoLiu-2020 ***@***.***> a
écrit :
