### ISSUE TITLE
Failed to Locate IDAPRO

### ISSUE THREAD

**Issue by aaaddress1** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#43]
Hi there,
I try to submit a binary to INDEXING tab but it displays like the following error:

2020-02-03 16:48:18.933 ERROR 4652 --- [nio-8571-exec-9] c.m.s.d.k.f.d.DisassemblyFactory         : Failed to retrieved IDA Path from registery

java.lang.NullPointerException: null
	at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.getIDAHome(DisassemblyFactoryIDA.java:101) [kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.<init>(DisassemblyFactoryIDA.java:92) [kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory.getDefaultDisassemblyFactory(DisassemblyFactory.java:77) [kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.app.clone.CloneSearchResources.<init>(CloneSearchResources.java:128) [kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.app.clone.asm.AsmApplicationMeta.getResource(AsmApplicationMeta.java:57) [kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.app.ApplicationMeta.submitJob(ApplicationMeta.java:102) [kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.app.clone.AbastractCloneSearchHandler.postBinary(AbastractCloneSearchHandler.java:154) [kam1n0-server.jar:2.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_231]

Thanks!

**Comment by DuckYellowPP** [comment]
I met the same ERROR

**Comment by DuckYellowPP** [comment]
Hey,friend.
I found out the solution.
Whether your system is Windows or Linux,you should change the vaule of "kam1n0.ida.home" in tht kam1n0 server pane
When you use a correct address of kam1n0.ida.home,the kam1n0 will work normally

**Comment by SimaArasteh** [comment]
Hey, I have the same issue. My OS is Linux and although I set the ida pro path in kam1n0.properties file, I get the same error.

java.io.FileNotFoundException: Failed to locate IDAPRO. The engine will not be able to disassemble. Check configuration or Try other implementation.java.io.FileNotFoundException: Failed to locate IDAPRO. The engine will not be able to disassemble. Check configuration or Try other implementation. at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.loadAsMultiPart(DisassemblyFactoryIDA.java:167) at ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory.loadAsMultiPart(DisassemblyFactory.java:63) at ca.mcgill.sis.dmas.kam1n0.app.clone.CloneSearchResources.disassembleIntoMultiPart(CloneSearchResources.java:150) at ca.mcgill.sis.dmas.kam1n0.app.clone.BinaryIndexProcedureLSHMR.lambda$runProcedure$1(BinaryIndexProcedureLSHMR.java:70) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at ca.mcgill.sis.dmas.kam1n0.app.clone.BinaryIndexProcedureLSHMR.runProcedure(BinaryIndexProcedureLSHMR.java:100) at ca.mcgill.sis.dmas.kam1n0.app.scheduling.LocalDmasJobProcedure.execute(LocalDmasJobProcedure.java:104) at org.quartz.core.JobRunShell.run(JobRunShell.java:202) at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
