### ISSUE TITLE
INDEX Error: Failed to disasemble the given file.

### ISSUE THREAD

**Issue by wwzcrack** [McGill-DMaS/Kam1n0-Plugin-IDA-Pro#66]
java.lang.Exception: Failed to disasemble the given file.
	at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.loadAsMultiPart(DisassemblyFactoryIDA.java:203) ~[kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory.loadAsMultiPart(DisassemblyFactory.java:63) ~[kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.app.clone.CloneSearchResources.disassembleIntoMultiPart(CloneSearchResources.java:150) ~[kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.app.clone.BinaryIndexProcedureLSHMR.lambda$runProcedure$1(BinaryIndexProcedureLSHMR.java:70) ~[kam1n0-server.jar:2.0.0]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:1.8.0_261]
	at ca.mcgill.sis.dmas.kam1n0.app.clone.BinaryIndexProcedureLSHMR.runProcedure(BinaryIndexProcedureLSHMR.java:100) ~[kam1n0-server.jar:2.0.0]
	at ca.mcgill.sis.dmas.kam1n0.app.scheduling.LocalDmasJobProcedure.execute(LocalDmasJobProcedure.java:104) ~[kam1n0-server.jar:2.0.0]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[kam1n0-server.jar:2.0.0]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[kam1n0-server.jar:2.0.0]

![index_error](https://user-images.githubusercontent.com/38138419/110090478-4d64fc00-7dd2-11eb-8a7e-f34e43ceb2a1.PNG)

**Comment by wwzcrack** [comment]
Kam1n0 v2.1 does not have this bug.
